### ISSUE TITLE
ERROR: gmmgWcbAmjo: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by ActionHank86** [dumrauf/youtube_to_audiobook#7]
Hi, I have tried to follow your instructions on Linux Mint 20.3 and get the following output:

VirtualBox:~$ docker run -v "$(pwd)":/data -u $(id -u ${USER}):$(id -g ${USER}) dumrauf/yt2ab:v1.3.0 -u "https://youtu.be/gmmgWcbAmjo?list=PLZ-bKJtH3G7BYYscYohAFZAq65RwCf-K-"

[INFO  tini (1)] Spawned child process 'yt2ab' with pid '7'
ERROR: gmmgWcbAmjo: YouTube said: Unable to extract video data
[INFO  tini (1)] Main child exited normally (with status '0')

Any ideas?

**Comment by dumrauf** [comment]
Hi @ActionHank86,

Thanks for creating the ticket.

I get the feeling that the error you're experiencing might be down to the version of `youtube-dl`.

As for a solution, it seems that [`yt-dlp`](https://github.com/yt-dlp/yt-dlp) (note the extra 'p' at the end) has gained some traction recently. You might be able to achieve similar results via
```
yt-dlp --embed-thumbnail --extract-audio  --add-metadata --audio-format mp3 "https://youtu.be/gmmgWcbAmjo?list=PLZ-bKJtH3G7BYYscYohAFZAq65RwCf-K-"
```

**Comment by ActionHank86** [comment]
Thank you, that works too :)
